config/routes.rb
MovieLibrary::Application.routes.draw do
	get 'admin' => 'admin#index'

	controller :session do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
	end

  resources :users

  resources :orders

  resources :episode_items do
		post :order_all_episodes, :on => :member
	end

  resources :movie_items

  resources :carts

  resources :role_in_an_episodes

  resources :role_in_a_movies

  resources :actors

  get "home/index"

	resources :movies do 
		resources :comments			# /movies/:movie_id/comments/:id => CommentsController
	end

  resources :series do
		resources :comments
  	resources :episodes do 
			resources :comments
		end
	end

	match "rates" => "movies#rate"
	

  root :to => 'home#index'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	skip_before_filter :authorize, :only => [:show, :index]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
		@cart = current_cart

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :ok }
		  else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :ok }
    end
  end

  #VOTE
  def rate
	@movie = Movie.find(params[:id])
   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
	<div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>		
	</div>
	<div class ="field">
		<%= f.label :poster %><br />
		<%= f.file_field :pic %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/_form2.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Rating</th>
    <th>No. of votes</th>
		<th>Price</th>
		<th>Actors</th>
		<th>Poster</th>
    <th></th>
		<th></th>
  </tr>

<% @movies.sort_by(&:rating).reverse.each do |movie| %>
  <tr align="center" valign="middle">
    <td><%= movie.title %></td>
    <td><%= movie.display_rating %></td>
    <td><%= movie.number_of_votes %></td>
		<td><em><%= number_to_currency(movie.price) %></em></td>
		<td><% movie.actors.all.each do |actor| %>
				<%= link_to actor.name, actor %><br />
				<% end %></td>
		<td><%= image_tag movie.pic.url(:thumb), :alt => "No poster" %></td>
		<td><%= link_to 'Show', movie %>
				<%= link_to 'Edit', edit_movie_path(movie) %><br />
				<%= link_to 'Destroy', movie, confirm: 'Are you sure?', method: :delete %>
				<%= link_to 'Rate', :controller => "movies", :action => "rate", :id => movie %><br/>
				<%= link_to "Comments (#{movie.comments.all.count})", movie_comments_path(movie) %> </td>
		<td><%= button_to 'Order now', movie_items_path(:movie_id => movie), :disabled => !logged_in? %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %>
<%= link_to 'Home', root_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/rate.html.erb
<h2> <%= @movie.title %> </h2>
<p> <%= "Current rating: " %>
    <%= @movie.rating %> </p>

<%= render 'form2' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>
<table>
	<tr>
		<td valign="top">
			<p>
				<b>Title:</b>
				<%= @movie.title %>
			</p>

			<p>
				<b>Rating:</b>
				<%= @movie.display_rating %>
			</p>

			<p>
				<b>Price:</b>
				<em><%= number_to_currency(@movie.price) %></em>
			</p>

			<p>
				<b>Actors:</b>
			</p>

			<table>
				<tr>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
				</tr>

			<% @movie.actors.all.each do |actor| %>
				<tr>
					<td><%= actor.name %></td>
					<td><%= link_to 'Show', actor %></td>
					<td><%= link_to 'Edit', edit_actor_path(actor) %></td>
					<td><%= link_to 'Destroy', actor, confirm: 'Are you sure?', method: :delete %></td>
				</tr>
			<% end %>
			</table>
			<p><a class ="test">
				<%= button_to 'Order now', movie_items_path(:movie_id => @movie), :disabled => !logged_in? %>
			</a></p>
		</td>
		<td>
			<%= image_tag @movie.pic.url %>
		</td>
	</tr>
</table>
<br />

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Movies', movies_path %>