config/routes.rb
MovieLibrary::Application.routes.draw do
	get 'admin' => 'admin#index'

	controller :session do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
	end

  resources :users

  resources :orders

  resources :episode_items do
		post :order_all_episodes, :on => :member
	end

  resources :movie_items

  resources :carts

  resources :role_in_an_episodes

  resources :role_in_a_movies

  resources :actors

  get "home/index"

	resources :movies do 
		resources :comments			# /movies/:movie_id/comments/:id => CommentsController
	end

  resources :series do
		resources :comments
  	resources :episodes do 
			resources :comments
		end
	end

	match "rates" => "movies#rate"
	

  root :to => 'home#index'
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  validates :title, :presence => true
  validates :number, :presence => true, :uniqueness => {:scope => :series_id, :message => ": The episode with a provided number already exists."}

	after_create :increment_episodes_count
	after_destroy :decrement_episodes_count
	before_destroy :ensure_no_episode_items
	after_save :series_calculate_price
	after_destroy :series_calculate_price
	
	delegate :calculate_price, :prefix => true, :to => :series

  belongs_to :series
	has_many :episode_items
	has_many :comments, :as => :commentary

	protected
	
	def increment_episodes_count
		Series.increment_counter(:number_of_episodes, series.id)
	end

	def decrement_episodes_count
		Series.decrement_counter(:number_of_episodes, series.id)
	end

	private
	
	def ensure_no_episode_items
		if !episode_items
			return true
		elsif episode_items.empty?
			return true
		else
			errors.add(:base, 'Movie items exist')
			return false
		end
	end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
	skip_before_filter :authorize, :only => [:index, :show]
 
 respond_to :html, :json

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = series.episodes

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @episodes }
    end
  end
  # GET /episodes/1
  # GET /episodes/1.json
  def show
    @episode = series.episodes.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @episode }
    end
  end
 
  # GET /episodes/new
  # GET /episodes/new.json
  def new
		@episode = series.episodes.build

		respond_with([series, @episode])

  end

  # GET /episodes/1/edit
  def edit
    @episode = series.episodes.find(params[:id])
  end

  # POST /episodes
  # POST /episodes.json

	# TODO CHECK WHY DIDN'T WORK WITH RESPOND_WITH
  def create
    @episode = series.episodes.build(params[:episode])
    if @episode.save
			flash[:notice] = "Successfully created"
			redirect_to [series, @episode]
		else
			flash[:alert] = "erroren"
      render :new
		end

		# debugger

    # respond_with([@series, @episode])
  end

  # PUT /episodes/1
  # PUT /episodes/1.json
  def update
    @episode = series.episodes.find(params[:id])
		

		flash[:notice] = "Episode was successfully updated." if @episode.update_attributes(params[:episode])
		respond_with([series, @episode])

  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode = series.episodes.find(params[:id])
    @episode.destroy

		if @episode.destroyed?
			flash[:notice] = "Episode successfully destroyed." 
		else
			flash[:notice] = "Episode failed to get destroyed." 
		end
		respond_with([series, :episodes])
  end


  protected

	def series
    @series ||= Series.find(params[:series_id])
	end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<%= form_for([@series, @episode]) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
	<div class ="price">
		<%= f.label :price %><br />
		<%= f.text_field :price %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render 'form' %>

<%= link_to 'Show', [@series, @episode] %> |
<%= link_to 'Back', [@series, :episodes] %>

app/views/episodes/index.html.erb
<h2>Listing episodes</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Number</th>
		<th>Price</th>
    <th></th>
    <th></th>
  </tr>

<% @episodes.sort_by(&:number).each do |episode| %>
  <tr align ="center">
    <td><%= episode.title %></td>
    <td><%= episode.number %></td>
		<td><em><%= number_to_currency(episode.price) %></em></td>
    <td class="to_be_spaced">
			<%= link_to 'Show', [@series, episode] %>
		  <%= link_to 'Edit', [:edit, @series, episode] %>
		  <%= link_to 'Destroy', [@series, episode], confirm: 'Are you sure?', method: :delete %><br />
			<%= link_to "Comments (#{episode.comments.all.count})", series_episode_comments_path(@series, episode) %> </td>
		<td class="to_be_spaced"><%= button_to 'Order now', episode_items_path(:episode_id => episode), :disabled => !logged_in? %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Episode', [:new, @series, :episode] %>
<%= link_to 'Series list', series_index_path %>
<%= link_to 'Home', root_path %>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render 'form' %>

<%= link_to 'Back', [@series, :episodes] %>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @episode.title %>
</p>

<p>
  <b>Number:</b>
  <%= @episode.number %>
</p>

<p>
	<b>Price:</b>
	<em><%= number_to_currency(@episode.price)%></em>
</p>

<p>
	<%= button_to 'Order now', episode_items_path(:episode_id => @episode), :disabled => !logged_in? %>
</p>


<%= link_to 'Edit', [:edit, @series, @episode] %>
<%= link_to 'Back', [@series, :episodes] %>