config/routes.rb
MovieLibrary::Application.routes.draw do
	get 'admin' => 'admin#index'

	controller :session do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
	end

  resources :users

  resources :orders

  resources :episode_items do
		post :order_all_episodes, :on => :member
	end

  resources :movie_items

  resources :carts

  resources :role_in_an_episodes

  resources :role_in_a_movies

  resources :actors

  get "home/index"

	resources :movies do 
		resources :comments			# /movies/:movie_id/comments/:id => CommentsController
	end

  resources :series do
		resources :comments
  	resources :episodes do 
			resources :comments
		end
	end

	match "rates" => "movies#rate"
	

  root :to => 'home#index'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :movie_items	
	has_many :episode_items
	belongs_to :order
	belongs_to :user

	def add_movie(movie_id, movie_price)
		current_item = movie_items.find_by_movie_id(movie_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = MovieItem.new(:movie_id => movie_id, :quantity => 1)
			movie_items << current_item
		end
		current_item
	end

	def add_episode(episode_id,episode_price)
		current_item = episode_items.find_by_episode_id(episode_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = EpisodeItem.new(:episode_id => episode_id, :quantity => 1)
			episode_items << current_item
		end
		if current_item.save
			return current_item
		else
			return false
		end
	end

	def total_price
		tmp_price = 0
		movie_items.all.each do |item|
			tmp_price += item.movie.price * item.quantity
		end
		episode_items.all.each do |item|
			tmp_price += item.episode.price * item.quantity
		end
		tmp_price - discount
	end
	
	def add_all_episodes(series)
		series.episodes.all.each do |episode|
			add_episode(episode.id, episode.price)
		end
		update_discount(series.episodes.all.sum(&:price) * 0.1)
	end

	def discount_update_needed?(contr, series)
		series_episodes_in_cart_quantities = []

		episode_items.all.each do |item|
			series_episodes_in_cart_quantities << item.quantity if item.episode.series == series && item.quantity > 0
		end

		logger.info "dupa#{series_episodes_in_cart_quantities.count}"
		
		return true if contr == "c" && series_episodes_in_cart_quantities.count == series.episodes.count &&
											series_episodes_in_cart_quantities.max - series_episodes_in_cart_quantities.min == 0
		return true if contr == "d" && series_episodes_in_cart_quantities.count == series.episodes.count - 1
		return true if contr == "d"	&& series_episodes_in_cart_quantities.count == series.episodes.count &&
																	 series_episodes_in_cart_quantities.max - series_episodes_in_cart_quantities.min == 1 &&
																	 series_episodes_in_cart_quantities.find_all{|i| i == series_episodes_in_cart_quantities.max}.count == 																					series_episodes_in_cart_quantities.count - 1	
		return false
	end

	def update_discount(amount)
		update_attribute :discount, discount + amount
	end	
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	skip_before_filter :authorize, :only => [:create, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    redirect_to root_path, :notice => "You are not supposed to view this page."
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
		begin
			@cart = Cart.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			logger.error "Attempt to access invalid cart #{params[:id]}"
			redirect_to root_path, :notice => 'You are not supposed to view this page.'
			else
				redirect_to root_path, :notice => 'You are not supposed to view this page.'
		end
	end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
		redirect_to root_path
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])
		@cart.user = current_user

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.movie_items.destroy_all
		@cart.episode_items.destroy_all
		@cart.update_attribute :discount, 0

    respond_to do |format|
			format.html { redirect_to(root_path, :notice => 'Your cart is currently empty.') }
      format.json { head :ok }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<h2>Your cart</h2>

<table id="cart_rendered">
	<tr id="to_be_centered">
		<th colspan=2>Movie</th>
		<th id="to_be_spaced">Amount</th>
		<th id="to_be_spaced">Item Price</th>		
		<th id="to_be_spaced">Total Price</th>
		<th></th>
	</tr>
<% @cart.movie_items.each do |item| %>
	<tr id="to_be_centered">
		<td colspan=2><%= item.movie.title %></td>
		<td id="to_be_spaced"><%= item.quantity %></td>
		<td id="to_be_spaced"><%= number_to_currency(item.movie.price) %></td>
		<td id="to_be_spaced"><%= number_to_currency(item.total_price) %></td>		
		<td><%= button_to 'Remove item', item, :method => :delete %></td> 
	</tr>
<% end %>
	<tr id="to_be_centered">
		<th>Episode</th>
		<th id="to_be_spaced">Series</th>
		<th id="to_be_spaced">Amount</th>
		<th id="to_be_spaced">Item Price</th>
		<th id="to_be_spaced">Total Price</th>
		<th></th>
	</tr>
<% @cart.episode_items.all.sort_by{|e| e.episode.series.title}.each do |item| %>
	<tr id="to_be_centered">
		<td><%= item.episode.title %></td>
		<td id="to_be_spaced"><%= item.episode.series.title_shortened %></td>
		<td id="to_be_spaced"><%= item.quantity %></td>
		<td id="to_be_spaced"><%= number_to_currency(item.episode.price) %></td>
		<td id="to_be_spaced"><%= number_to_currency(item.total_price) %></td>		
		<td><%= button_to 'Remove item', item, :method => :delete %></td>
	</tr>
<% end %>
	<tr id ="total_line">
		<td></td>
		<td></td>
		<td></td>
		<td><b>Total:</b></td>
		<td><b><%= number_to_currency(@cart.total_price) %></b></td>
	</tr>
	<tr id ="total_line">
		<td></td>
		<td></td>
		<td></td>
		<td><b>(Discount:</b></td>
		<td><b><%= number_to_currency(@cart.discount) %>)</b></td>		
	</tr>
</table>

<div id="first_button">
	<%= button_to 'Empty cart', @cart, :method => :delete,
					:confirm => 'Are you sure?' %>
</div>
<div id="second_button">
	<%= button_to 'Proceed to payment', new_order_path, :method => :get %>
</div>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Your Orders</h2>
<%= render @cart %>