config/routes.rb
MovieLibrary::Application.routes.draw do
	get 'admin' => 'admin#index'

	controller :session do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
	end

  resources :users

  resources :orders

  resources :episode_items do
		post :order_all_episodes, :on => :member
	end

  resources :movie_items

  resources :carts

  resources :role_in_an_episodes

  resources :role_in_a_movies

  resources :actors

  get "home/index"

	resources :movies do 
		resources :comments			# /movies/:movie_id/comments/:id => CommentsController
	end

  resources :series do
		resources :comments
  	resources :episodes do 
			resources :comments
		end
	end

	match "rates" => "movies#rate"
	

  root :to => 'home#index'
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
	skip_before_filter :authorize, :only => [:index, :show]
 
 # GET /series
  # GET /series.json
  def index
    @series = Series.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @series }
    end
  end

  # GET /series/1
  # GET /series/1.json
  def show
    @series = Series.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @series }
    end
  end

  # GET /series/new
  # GET /series/new.json
  def new
    @series = Series.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @series }
    end
  end

  # GET /series/1/edit
  def edit
    @series = Series.find(params[:id])
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(params[:series])

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.json { render json: @series, status: :created, location: @series }
      else
        format.html { render action: "new" }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /series/1
  # PUT /series/1.json
  def update
    @series = Series.find(params[:id])

    respond_to do |format|
      if @series.update_attributes(params[:series])
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series = Series.find(params[:id])
    @series.destroy

    respond_to do |format|
      format.html { redirect_to series_index_url }
      format.json { head :ok }
    end
  end

end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= form_for(@series) do |f| %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
	<p>	
		<b> Poster </b><br />
		<%= f.file_field :pic %>
	</p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/series/edit.html.erb
<h1>Editing series</h1>

<%= render 'form' %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_index_path %>

app/views/series/index.html.erb
<h1>Listing series</h1>

<table>
  <tr>
    <th>Title</th>
    <th>No. of Episodes</th>
		<th>Price*</th>
		<th>Poster</th>
    <th></th>
    <th></th>
  </tr>

<% @series.each do |series| %>
  <tr align="center" valign="middle">
    <td><%= series.title %></td>
    <td><%= series.number_of_episodes %></td>
		<td><em><%= number_to_currency(series.price) %></em></td>
		<td><%= image_tag series.pic.url(:thumb), :alt => "No poster"%></td>
    <td><%= link_to 'Show', series %>
				<%= link_to 'Edit', edit_series_path(series) %>
				<%= link_to 'Destroy', series, confirm: 'Are you sure?', method: :delete %><br />
    		<%= link_to 'Show episodes', [series, :episodes] %><br />
				<%= link_to "Comments (#{series.comments.all.count})", series_comments_path(series) %> </td></td>
		<td><%= button_to 'Order all episodes', order_all_episodes_episode_item_path(series), :disabled => !logged_in? %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Series', new_series_path %>
<%= link_to 'Home', root_path %>

<h6>*Ordering a whole series, you get a 10% discount on its episodes.</h6>

app/views/series/new.html.erb
<h1>New series</h1>

<%= render 'form' %>

<%= link_to 'Back', series_index_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>
<table>
	<tr>
		<td  valign="top">
			<p>
				<b>Title:</b>
				<%= @series.title %>
			</p>

			<p>
				<b>No. of Episodes:</b>
				<%= @series.number_of_episodes %>
			</p>

			<p>
				<b> Episodes: </b>
			</p>

			<table>
				<tr>
					<th>Title</th>
					<th>Number</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>

			<% @series.episodes.sort_by(&:number).each do |episode| %>
				<tr>
					<td><%= episode.title %></td>
					<td><%= episode.number %></td>
					<td><%= link_to 'Show', [@series, episode] %></td>
					<td><%= link_to 'Edit', [:edit, @series, episode] %></td>
					<td><%= link_to 'Destroy', [@series, episode], confirm: 'Are you sure?', method: :delete %></td>
				</tr>
			<% end %>
			</table>
		</td>
		<td>
			<%= image_tag @series.pic.url, :alt => "Picture missing" %>
		</td>

</table>
<p>


</p>
<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>